import { defineConfig } from "tsup";
export default defineConfig({
    entry: ["src/bin/p2p-node.ts"],
    format: ["esm"],
    clean: true,
    minify: true,
    sourcemap: true,
    target: "node20",
    platform: "node",
    shims: true,
    noExternal: [
        "commander",
        "@chainsafe/*",
        "@libp2p/*",
        "libp2p",
        "events",
        "fs",
        "path",
        "os",
        "readline",
        "child_process",
        "dotenv",
        "eciesjs",
        "secp256k1",
        "viem",
        "uint8arrays",
        "@multiformats/*",
    ],
});
//# sourceMappingURL=tsup.config.js.map